Models/Shared.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FCMS_RUDA.Models
{
    public class Shared
    {

    }
}

Controllers/EFileController.cs
using com.ruda.Efile.BusinessLogic;
using com.ruda.Efile.Domain;
using DAL;
using FCMS_RUDA.Models;
using FCMS_RUDA.Shared;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Renci.SshNet;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FCMS_RUDA.Controllers
{
    public class EFileController : Controller
    {
        private readonly SftpConfig sftpConfig;
        private readonly WebAPI webAPI;

        public EFileController(IOptions<SftpConfig> _SftpConfig, IOptions<WebAPI> _webAPI)
        {
            this.sftpConfig = _SftpConfig.Value;
            this.webAPI = _webAPI.Value;
        }


        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("ID") == null)
            {
                TempData["Session"] = "Your Session has expired. Please Login again";
                return RedirectToAction("Logout", "Users");
            }
            Employees emp = HttpContext.Session.GetComplexData<Employees>("Employee");

            DataTable dt = new EFileDAL().GetMyFiles(emp.EmpID);

            //dt.Columns.Add("DesignationName", typeof(string));
            dt.Columns.Add("DepartmentName", typeof(string));
            dt.Columns.Add("DeptInitials", typeof(string));

            foreach (DataRow row in dt.Rows)
            {
                Department dept = HttpContext.Session.GetComplexData<List<Department>>("Departments").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedTodept"]));
                //Designation design = HttpContext.Session.GetComplexData<List<Designation>>("Designations").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedToDesig"]));
                //row["DesignationName"] = row["MarkedToDesig"].ToString();
                row["DepartmentName"] = dept.Name;
                row["DeptInitials"] = dept.Initials;
            }

            return View(dt);
        }

        public IActionResult MyDeptFiles()
        {
            if (HttpContext.Session.GetString("ID") == null)
            {
                TempData["Session"] = "Your Session has expired. Please Login again";
                return RedirectToAction("Logout", "Users");
            }

            Employees emp = HttpContext.Session.GetComplexData<Employees>("Employee");
            DataTable dt = new EFileDAL().GetMyDeptFiles(emp.Department);

            //dt.Columns.Add("DesignationName", typeof(string));
            dt.Columns.Add("DepartmentName", typeof(string));
            dt.Columns.Add("DeptInitials", typeof(string));

            foreach (DataRow row in dt.Rows)
            {
                Department dept = HttpContext.Session.GetComplexData<List<Department>>("Departments").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedTodept"]));
                //Designation design = HttpContext.Session.GetComplexData<List<Designation>>("Designations").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedToDesig"]));
                //row["DesignationName"] = design.Title;
                row["DepartmentName"] = dept.Name;
                row["DeptInitials"] = dept.Initials;
            }

            return View(dt);
        }

        public IActionResult FilesClosed()
        {
            if (HttpContext.Session.GetString("ID") == null)
            {
                TempData["Session"] = "Your Session has expired. Please Login again";
                return RedirectToAction("Logout", "Users");
            }
            Employees emp = HttpContext.Session.GetComplexData<Employees>("Employee");
            DataTable dt = new EFileDAL().GetMyClosedFiles(emp.EmpID);

            //dt.Columns.Add("DesignationName", typeof(string));
            dt.Columns.Add("DepartmentName", typeof(string));
            dt.Columns.Add("DeptInitials", typeof(string));

            foreach (DataRow row in dt.Rows)
            {
                Department dept = HttpContext.Session.GetComplexData<List<Department>>("Departments").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedTodept"]));
                //Designation design = HttpContext.Session.GetComplexData<List<Designation>>("Designations").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedToDesig"]));
                //row["DesignationName"] = design.Title;
                row["DepartmentName"] = dept.Name;
                row["DeptInitials"] = dept.Initials;
            }

            return View(dt);
        }

        public IActionResult PendingFiles()
        {
            if (HttpContext.Session.GetString("ID") == null)
            {
                TempData["Session"] = "Your Session has expired. Please Login again";
                return RedirectToAction("Logout", "Users");
            }
            Employees emp = HttpContext.Session.GetComplexData<Employees>("Employee");
            DataTable dt = new EFileDAL().GetMyPendingFiles(emp.EmpID);

            //dt.Columns.Add("DesignationName", typeof(string));
            dt.Columns.Add("DepartmentName", typeof(string));
            dt.Columns.Add("DeptInitials", typeof(string));

            foreach (DataRow row in dt.Rows)
            {
                Department dept = HttpContext.Session.GetComplexData<List<Department>>("Departments").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedTodept"]));
                //Designation design = HttpContext.Session.GetComplexData<List<Designation>>("Designations").ToList().First(x => x.ID == Convert.ToInt32(row["MarkedToDesig"]));
                //row["DesignationName"] = design.Title;
                row["DepartmentName"] = dept.Name;
                row["DeptInitials"] = dept.Initials;
            }

            return View(dt);
        }

        public IActionResult FileRequests()
        {
            if (HttpContext.Session.GetString("ID") == null)
            {
                TempData["Session"] = "Your Session has expired. Please Login again";
                return RedirectToAction("Logout", "Users");
            }
            Employees emp = HttpContext.Session.GetComplexData<Employees>("Employee");
            DataTable dt = new EFileDAL().GetPendingFileRequests(emp.EmpID);
            return View(dt);
        }

        public IActionResult ViewFile(int FileID)
        {
            if (HttpContext.Session.GetString("ID") == null)
            {
                TempData["Session"] = "Your Session has expired. Please Login again";
                return RedirectToAction("Logout", "Users");
            }

            List<Department> Depts = HttpContext.Session.GetComplexData<List<Department>>("Departments");
            //List<Designation> Designs = HttpContext.Session.GetComplexData<List<Designation>>("Designations");

            EFile file = new EFileDAL().GetFilebyIDforView(FileID, Depts);

            List<DocumentPriority> listPriority = new FilesDAL().GetAllDocumentPriorities();
            ViewBag.ListPriority = listPriority;

            List<DocumentType> listtypes = new FilesDAL().GetAllDocumentTypes();
            ViewBag.ListTypes = listtypes;

            List<DocumentStatus> listStatuses = new FilesDAL().GetAllDocumentStatus();
            ViewBag.ListStatus = listStatuses;

            return View(file);
        }

        public IActionResult AddNewFile()
        {
            if (HttpContext.Session.GetString("ID") == null)
            {
                TempData["Session"] = "Your Session has expired. Please Login again";
                return RedirectToAction("Logout", "Users");
            }

            List<Department> lstdept = HttpContext.Session.GetComplexData<List<Department>>("Departments");
            ViewBag.ListDepts = lstdept;

            List<DocumentPriority> listPriority = new FilesDAL().GetAllDocumentPriorities();
            ViewBag.ListPriority = listPriority;

            List<DocumentType> listtypes = new FilesDAL().GetAllDocumentTypes();
            ViewBag.ListTypes = listtypes;

            List<DocumentStatus> listStatuses = new FilesDAL().GetAllDocumentStatus();
            ViewBag.ListStatus = listStatuses;

            Employees emp = HttpContext.Session.GetComplexData<Employees>("Employee");
            ViewBag.MarkedToDept = Convert.ToInt32(emp.Department);

            List<Employees> listEmp = new UsersBLL().GetEmployeesForNewFileMark(emp.Department, emp.Grade, webAPI);
            ViewBag.ListEmp = listEmp;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddNewFile(EFileViewModel viewModel)
        {
            List<DocumentPriority> listPriority = new FilesDAL().GetAllDocumentPriorities();
            ViewBag.ListPriority = listPriority;

            List<DocumentType> listtypes = new FilesDAL().GetAllDocumentTypes();
            ViewBag.ListTypes = listtypes;

            List<DocumentStatus> listStatuses = new FilesDAL().GetAllDocumentStatus();
            ViewBag.ListStatus = listStatuses;

            Employees emp = HttpContext.Session.GetComplexData<Employees>("Employee");

            List<Employees> listUsers = new UsersBLL().GetEmployeesForNewFileMark(emp.Department, emp.Grade, webAPI);
            ViewBag.ListUsers = listUsers;

            int UserID = Convert.ToInt32(HttpContext.Session.GetString("ID"));

            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                int maxnumber = new EFileDAL().GetMaxDocNumber(Convert.ToInt32(HttpContext.Session.GetString("Department")));
                viewModel.File.FileNumber = "RUDA-" + emp.WingInitials + "-" + emp.DeptInitials + "-" + DateTime.Now.Year + "-" + maxnumber;

                if (viewModel != null && viewModel.FileAttachments.FileAttachment != null && viewModel.FileAttachments.FileAttachment.Length > 0)
                {

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using FCMS_RUDA.Models;
@using com.ruda.Efile.Domain;

@inject IHttpContextAccessor HttpContextAccessor

@{
    List<UserPermissions> permissions = HttpContextAccessor.HttpContext.Session.GetComplexData<List<UserPermissions>>("Permissions");
    Employees objemp = HttpContextAccessor.HttpContext.Session.GetComplexData<Employees>("Employee");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="~/Theme/assets/img/favicon.png">

    <title>
        E File System
    </title>

    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <link href="~/Theme/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/Theme/assets/css/nucleo-svg.css" rel="stylesheet" />
    <link href="~/Theme/assets/css/nucleo-svg.css" rel="stylesheet" />
    <link href="~/Theme/assets/css/argon-dashboard.css?v=2.0.0" id="pagestyle" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body class="g-sidenav-show bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main" @*data-color="dark"*@>
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <img src="~/Theme/assets/img/logo2.png" class="navbar-brand-img h-200" alt="main_logo" />
            <span class="ms-1 font-weight-bold">E-File System</span>
        </div>
        @*<hr class="horizontal dark mt-0">*@
        <hr />
        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <nav class='animated bounceInDown custom-nav'>
                <ul>
                    @if (permissions.Any(x => x.ModuleID == 1 && x.ScreenID == 1 && x.PView == true))
                    {
                        <li><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
                    }
                    @if (permissions.Any(x => x.ModuleID == 1 && x.ScreenID == 1 && x.PView == true))
                    {
                        <li><a href="@Url.Action("UpdateUser", "Users", new  { UserID = Convert.ToInt32(@HttpContextAccessor.HttpContext.Session.GetString("ID").ToString())})">My Profile</a></li>
                    }
                    @if (permissions.Any(x => x.ModuleID == 2 && x.PView == true))
                    {
                        <li class='sub-menu'>
                            <a href="#">User Management<div class='fa fa-caret-down right'></div></a>
                            <ul>
                                @if (permissions.Any(x => x.ScreenID == 3 && x.PView == true && x.PAdd == true))
                                {
                                    <li><a href="@Url.Action("AddNewUser", "Users")" class="text-sm text-sm-left">Add New User</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 2 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("Index", "Users")" class="text-sm text-sm-left">Users List</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 4 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("UserRoles", "Users")" class="text-sm text-sm-left">User Types</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 5 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("UserPermissions", "Users")" class="text-sm text-sm-left">User Permissions</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 9 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("Departments", "Users")" class="text-sm text-sm-left">Departments</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 9 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("Designations", "Users")" class="text-sm text-sm-left">Designations</a></li>
                                }
                            </ul>
                        </li>
                    }
                    @if (permissions.Any(x => x.ModuleID == 3))
                    {
                        <li class='sub-menu' hidden>
                            <a href="#">Document Management<div class='fa fa-caret-down right'></div></a>
                            <ul>
                                @if (permissions.Any(x => x.ScreenID == 6 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("Index", "Files")" class="text-sm text-sm-left">Documents List</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 7 && x.PView == true && x.PAdd == true))
                                {
                                    <li><a href="@Url.Action("AddNewFile", "Files")" class="text-sm text-sm-left">Create New Document</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 8 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("DocumentTypes", "Files")" class="text-sm text-sm-left">Document Types</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 9 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("Departments", "Files")" class="text-sm text-sm-left">Departments</a></li>
                                }
                            </ul>
                        </li>
                    }
                    @if (permissions.Any(x => x.ModuleID == 3))
                    {
                        <li class='sub-menu'>
                            <a href="#">E-Files<div class='fa fa-caret-down right'></div></a>
                            <ul>
                                @if (permissions.Any(x => x.ScreenID == 8 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("FileRequests", "EFile")" class="text-sm text-sm-left">File Requests</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 6 && x.PView == true))
                                {
                                    <li><a href="@Url.Action("Index", "EFile")" class="text-sm text-sm-left">My Files</a></li>
                                }
                                @if (permissions.Any(x => x.ScreenID == 7 && x.PView == true && x.PAdd == true))
                                {
                                    <li><a href="@Url.Action("AddNewFile", "EFile")" class="text-sm text-sm-left">Create New</a></li>
                                }
                            </ul>
                        </li>
                    }
                    @if (permissions.Any(x => x.ModuleID == 4))
                    {
                        <li class='sub-menu'>
                            <a href="#">Reports<div class='fa fa-caret-down right'></div></a>
                            <ul>
                                <li><a href="#" class="text-sm text-sm-left">Documents</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </nav>
        </div>
        <div class="sidenav-footer mx-3 ">
            <a class="btn btn-primary btn-sm mb-0 w-100" href="@Url.Action("Logout","Users")" type="button">Logout</a>
        </div>
    </aside>
    <main class="main-content position-relative border-radius-lg ">
        <!-- Navbar -->
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
            <div class="container-fluid py-1 px-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5" hidden>
                        <li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="javascript:;">Pages</a></li>
                        <li class="breadcrumb-item text-sm text-white active" aria-current="page">Dashboard</li>
                    </ol>
                    <h6 class="font-weight-bolder text-white mb-0">@ViewData["Title"]</h6>
                </nav>
                <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 justify-content-end" id="navbar">
                    <ul class="navbar-nav justify-content-end text-right">
                        <li class="nav-item d-flex align-items-center">
                            <a href="javascript:;" class="nav-link text-white font-weight-bold px-0">
                                <div class="flex-lg-grow-1">
                                    <span class="fw-semibold d-block"><i class="fa fa-user me-sm-1"></i>@objemp.Name</span>
                                    <small class="fw-semibold d-block">@objemp.DesignationName - @objemp.DeptInitials</small>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Navbar -->
        <div class="container-fluid py-4">
            <div class="content-wrapper">
                <div class="content">
                    @RenderBody()
                </div>
                <footer class="footer pt-3">
                    <div class="container-fluid">
                        <div class="row align-items-center justify-content-lg-between">
                            <div class="col-lg-6 mb-lg-0 mb-4">
                                <div class="copyright text-center text-sm text-muted text-lg-start">
                                    ©
                                    <script>document.write(new Date().getFullYear())</script>,
                                    Copyright
                                    <a href="https://ruda.gov.pk/" class="font-weight-bold" target="_blank">Ravi Urban Development Authority</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </main>
    <!--   Core JS Files   -->
    <script src="~/Theme/assets/js/core/popper.min.js"></script>
    <script src="~/Theme/assets/js/core/bootstrap.min.js"></script>
    <script src="~/Theme/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/Theme/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="~/Theme/assets/js/plugins/chartjs.min.js"></script>
    <script src="~/Theme/assets/js/argon-dashboard.min.js?v=2.0.0"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript">
        jQuery('.sub-menu ul').hide();
        jQuery(".sub-menu a").click(function () {
            jQuery(this).parent(".sub-menu").children("ul").slideToggle("100");
            jQuery(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
        });
    </script>
</body>
</html>